CREATE TABLE Libros(
    LibroID CHAR(5) CONSTRAINT PK_LIBROS PRIMARY KEY,
    Titulo VARCHAR2(20) CONSTRAINT NN_TITULO NOT NULL CONSTRAINT U_TITULO UNIQUE,
    Tipo VARCHAR2(10) CONSTRAINT CK_TIPO CHECK (LOWER(Tipo)IN('novela', 'terror', 'misterio')),
    Editor VARCHAR2(25),
    FechaEdicion DATE
);

DESC Libros;
SELECT * FROM USER_TABLES;
SELECT * FROM USER_TAB_COLUMNS WHERE LOWER(TABLE_NAME)='libros';