/* CREACI�N TABLA CON CAMPOS, SIN RESTRICCIONES */
CREATE TABLE P_EMPLEADOS(
IDEMPLEADO NUMBER(5),
NOMBRE VARCHAR2(30),
DIRECCION VARCHAR2(50),
CP CHAR(5),
POBLACION VARCHAR2(30),
PROVINCIA VARCHAR2(30),
FNACIMIENTO DATE,
FCONTRATO DATE,
JEFE NUMBER(5));

/* CREACI�N TABLA CON CAMPOS Y RESTRICCIONES SIN NOMBRE PERSONALIZADO 
(EL NOMBRE DE LA RESTRICCI�N LO PONE EL SISTEMA - ORACLE (SYS_N�MERO) */

CREATE TABLE P_EMPLEADOS(
IDEMPLEADO NUMBER(5) PRIMARY KEY,
NOMBRE VARCHAR2(30)  UNIQUE NOT NULL,
DIRECCION VARCHAR2(50),
CP CHAR(5)  CHECK (CP BETWEEN 48001 AND 48999),
POBLACION VARCHAR2(30) DEFAULT 'BILBAO',
PROVINCIA VARCHAR2(30),
FNACIMIENTO DATE,
FCONTRATO DATE,
JEFE NUMBER(5)  REFERENCES P_EMPLEADOS);


/* CREACI�N TABLA CON CAMPOS Y RESTRICCIONES CON NOMBRE PERSONALIZADO */

CREATE TABLE P_EMPLEADOS(
IDEMPLEADO NUMBER(5) CONSTRAINT PK_P_EMPLEADOS PRIMARY KEY,
NOMBRE VARCHAR2(30) CONSTRAINT UK_NOMBRE UNIQUE CONSTRAINT NN_NOMBRE NOT NULL,
DIRECCION VARCHAR2(50),
CP CHAR(5) CONSTRAINT CK_CP CHECK (CP BETWEEN 48001 AND 48999),
POBLACION VARCHAR2(30) DEFAULT 'BILBAO',
PROVINCIA VARCHAR2(30),
FNACIMIENTO DATE,
FCONTRATO DATE,
JEFE NUMBER(5) CONSTRAINT FK_JEFE_IDEMPLEADO REFERENCES P_EMPLEADOS);

/*MOSTRAR DESCRIPCI�N DE LOS CAMPOS DE LAS TABLAS*/

DESC P_EMPLEADOS;

/*MOSTRAR DATOS DE LAS TABLAS DEL USUARIO CON EL QUE ESTAMOS TRABAJANDO*/

SELECT * FROM USER_TABLES;

/*MOSTRAR DATOS DE LAS TABLAS DE TODOS LOS USUARIOS DEL SISTEMA*/

SELECT * FROM ALL_TABLES;

/*MOSTRAR DATOS DE LAS COLUMNAS DE LAS TABLAS*/

SELECT * FROM USER_TAB_COLUMNS WHERE lower(TABLE_NAME)='p_empleados';

/*MOSTRAR INFORMACI�N SOBRE LAS RESTRICCIONES*/

SELECT * FROM USER_CONSTRAINTS WHERE lower(TABLE_NAME)='p_empleados';

/*ELIMINAR TABLA*/

DROP TABLE P_EMPLEADOS;


/* CREAR TABLAS CON RESTRICCIONES DE 2º TIPO*/
CREATE TABLE P_EMPLEADOS(
IDEMPLEADO NUMBER(5),
NOMBRE VARCHAR2(30) NOT NULL,
DIRECCION VARCHAR2(50),
CP CHAR(5),
POBLACION VARCHAR2(30),
PROVINCIA VARCHAR2(30),
FNACIMIENTO DATE,
FCONTRATO DATE,
JEFE NUMBER(5),
CONSTRAINT PK_P_EMPLEADOS PRIMARY KEY(IDEMPLEADO),
CONSTRAINT UK_NOMBRE UNIQUE(NOMBRE),
CONSTRAINT CK_CP CHECK (CP BETWEEN 48001 AND 48999),
CONSTRAINT FK_JEFE_IDEMPLEADO FOREIGN KEY (JEFE) REFERENCES P_EMPLEADOS
);

/* CREAR TABLA CON CLAVE PRINCIPAL SOBRE 2 CAMPOS 
(Cuando se crea una restricci�n sobre m�s de 1 campo se debe emplear una restricci�n de tipo 2 ,
se crea al finalizar la definci�n de todos los campos*/

CREATE TABLE P_PRODUCTOS(
IDFABRICANTE NUMBER(5),
IDPRODUCTO CHAR(5),
STOCK NUMBER(10) DEFAULT 100,
PUNITARIO NUMBER(5,2),
CONSTRAINT PK_P_PRODUCTOS PRIMARY KEY(IDFABRICANTE,IDPRODUCTO));

SELECT * FROM USER_CONSTRAINTS WHERE UPPER(TABLE_NAME)='P_PRODUCTOS';
SELECT * FROM USER_CONS_COLUMNS WHERE UPPER(TABLE_NAME)='P_PRODUCTOS';

/***********************HASTA AQUÍ****************************************************/
/*NO VISTO DE MOMENTO*/
/* Crear una tabla con todos o parte de los datos de otra tabla*/ 

CREATE TABLE NUEVOS_CLIENTES AS SELECT * FROM clientes;

DESC NUEVOS_CLIENTES;

SELECT * FROM USER_CONSTRAINTS WHERE UPPER(TABLE_NAME)='CLIENTES';

SELECT * FROM USER_CONSTRAINTS WHERE UPPER(TABLE_NAME)='NUEVOS_CLIENTES';

/*Como pod�is observar si revis�is estas 3 instrucciones posteriores a la creaci�n es que la instrucci�n:

        CREATE TABLE NUEVA AS SELECT .......;
        
Crear los campos que has puesto en la select y tambi�n copia los datos insertados en ella, pero no copia ninguna de las restricciones,
por tanto en la nueva tabla no existe CLAVE PRINCIPAL, ni EXTRANJERA, al contrario que en la tabla de CLIENTES*/        


CREATE TABLE NUEVOS_PEDIDOS AS SELECT codigo,numpedido,fpedido FROM pedidos WHERE EXTRACT(YEAR FROM fpedido)>2000;

DESC NUEVOS_PEDIDOS;

SELECT * FROM NUEVOS_PEDIDOS;

SELECT * FROM USER_CONSTRAINTS WHERE UPPER(TABLE_NAME)='PEDIDOS';
/*La tabla PEDIDOS tiene 3 restricciones*/

SELECT * FROM USER_CONSTRAINTS WHERE UPPER(TABLE_NAME)='NUEVOS_PEDIDOS';
/*La tabla NUEVOS_PEDIDOS NO tiene restricciones*/
