/*ALTER TABLE: MODIFICAR TABLAS*/


/*DESC: Vemos los campos y tipos de datos de los campos, además de qué campos son NO NULOS (Datos necesarios)*/
DESC P_EMPLEADOS;
DESC EMPLEADOSB;
DESC P_OFICINAS;

/*Vista USER_CONSTRAINTS: Muestra todas las restricciones (CONSTRAINTS) de las tablas de mi espacio*/

SELECT * FROM USER_CONSTRAINTS WHERE lower(table_name)='empleadosb'; /*USER_CONSTRAINTS: Detalles de la Restricci�n*/
SELECT * FROM USER_CONS_COLUMNS WHERE lower(table_name)='p_empleados'; /*USER_CONS_CLUMNS: Campos que forman parte de la restricci�n*/
SELECT * FROM USER_CONSTRAINTS WHERE lower(table_name)='p_oficinas';  
SELECT * FROM p_ofiCINAS;

/* MODIFICAR TABLAS*/

/* A�adir 1 campo (movil:char (9)) a la tabla P_EMPLEADOS*/
ALTER TABLE P_EMPLEADOS ADD MOVIL CHAR(9) CONSTRAINT UK_MOVIL_EMPLEADO UNIQUE;

/*A�adir 2 o m�s campos (telefono:CHAR(9),correo VARCHAR2(50)) a la tabla P_EMPLEADOS*/
ALTER TABLE P_EMPLEADOS ADD 
(TELEFONO CHAR(9) NOT NULL ,
CORREO VARCHAR2(50) CONSTRAINT CK_CORREO_EMPLEADO CHECK (lower(correo) like '%@gmail.com' OR lower(correo) like '%@hotmail.com')
);


/* MODIFICAMOS TIPO del campo OFICINA de la tabla P_EMPLEADOS*/
ALTER TABLE P_EMPLEADOS MODIFY OFICINA CHAR(2);

/* DESHABILITAR RESTRICCI�N DE CLAVE FOR�NEA SOBRE CAMPO OFICINA de la tabla P_EMPLEADOS*/
ALTER TABLE P_EMPLEADOS DISABLE CONSTRAINT FK_OFICINA;

/* HABILITAR LA RESTRICCI�N DE CLAVE PRINCIPAL DE OFICINAS*/
ALTER TABLE P_OFICINAS ENABLE CONSTRAINT PK_P_OFICINAS;

/* ELIMINAR LA RESTRICCI�N DE CLAVE FOR�NEA DEL CAMPO OFICINA DE LA TABLA DE EMPLEADOS (RESTRICCI�N DE CLAVE FOR�NEA) */
ALTER TABLE P_EMPLEADOS DROP CONSTRAINT FK_OFICINA;



/*A�ADIR LA RESTRICCI�N ELIMINADA SOBRE EL CAMPO OFICINA DE LA TABLA DE EMPLEADOS (RESTRICCI�N DE CLAVE FOR�NEA)*/
ALTER TABLE P_EMPLEADOS 
    ADD CONSTRAINT FK_OFICINAS FOREIGN KEY (OFICINA) REFERENCES P_OFICINAS;

ALTER TABLE P_EMPLEADOS
    ADD CONSTRAINT U_TELEFONO UNIQUE(telefono);


/* CAMBIAR NOMBRE A UN CAMPO (EMAIL POR CORREO) en la tabla P_EMPLEADOS*/

ALTER TABLE P_EMPLEADOS RENAME COLUMN CORREO TO EMAIL;

/*MODIFICAR EL NOMBRE DE LA TABLA (CAMBIAR P_EMPLEADOS POR EMPLEADOSB)*/
ALTER TABLE P_EMPLEADOS RENAME TO EMPLEADOSB;

/*ELIMINAR UNA RESTRICCI�N EN LA TABLA EMPLEADOSB*/

ALTER TABLE EMPLEADOSB DROP CONSTRAINT CK_CORREO_EMPLEADO;

/*ELIMINAR UN CAMPO EN LA TABLA EMPLEADOSB*/

ALTER TABLE EMPLEADOSB DROP COLUMN EMAIL;
