-- 1
CREATE TABLE P_OFICINAS (
oficina NUMBER(2) CONSTRAINT PK_P_OFICINAS PRIMARY KEY,
ciudad CHAR(15),
region CHAR(10) CONSTRAINT CK_region CHECK(LOWER(region) IN ('norte','sur','este','oeste')),
dir NUMBER(3),
objetivo NUMBER(10),
ventas NUMBER(10)
);

CREATE TABLE P_EMPLEADOS (
numEmp NUMBER(3) CONSTRAINT PK_P_EMPLEADOS PRIMARY KEY,
nombre CHAR(20) CONSTRAINT NN_nombre NOT NULL CONSTRAINT U_nombre UNIQUE,
edad NUMBER(2) CONSTRAINT CK_edad CHECK(edad BETWEEN 18 AND 65),
oficina NUMBER(2) CONSTRAINT FK_EMPLEADOS_OFICINAS REFERENCES P_OFICINAS,
titulo CHAR(25) CONSTRAINT CK_titulo CHECK(LOWER(titulo) IN ('representante','dir ventas','dir general')),
contrato DATE,
jefe NUMBER(3),
cuota NUMBER(10),
ventas NUMBER(10)
);

CREATE TABLE P_CLIENTES (
numClie NUMBER(4) CONSTRAINT PK_P_CLIENTES PRIMARY KEY,
nombre CHAR(25) CONSTRAINT NN_nombre_clientes NOT NULL CONSTRAINT U_nombre_clientes UNIQUE,
repClie NUMBER(3) CONSTRAINT FK_EMPLEADOS_CLIENTES REFERENCES P_EMPLEADOS,
limiteCredito NUMBER(9) DEFAULT 20000
);

CREATE TABLE P_PRODUCTOS (
idFab CHAR(3),
idProducto CHAR(5),
descripcion CHAR(20) CONSTRAINT NN_descripcion NOT NULL,
precio NUMBER(4),
existencias NUMBER(3),
CONSTRAINT PK_PRODUCTOS PRIMARY KEY(idFab, idProducto),
CONSTRAINT CK_precio CHECK(precio > 0)
);

CREATE TABLE P_PEDIDOS (
codigo NUMBER(3) CONSTRAINT PK_P_PEDIDOS PRIMARY KEY,
numPedido NUMBER(6),
fechaPedido DATE,
cliente NUMBER(4) CONSTRAINT FK_PEDIDOS_CLIENTES REFERENCES P_CLIENTES,
representante CONSTRAINT FK_PEDIDOS_EMPLEADOS REFERENCES P_EMPLEADOS,
fabricante CHAR(3),
producto CHAR(5),
cantidad NUMBER(2),
importe NUMBER(10),
CONSTRAINT FK_PEDIDOS_PRODUCTOS FOREIGN KEY (fabricante, producto) REFERENCES P_PRODUCTOS(idFab, idProducto),
CONSTRAINT CK_cantidad CHECK(cantidad > 0)
);

-- 2
ALTER TABLE P_CLIENTES ADD (mail CHAR(20) CONSTRAINT CK_mail CHECK(mail LIKE ('%@%')), movil CHAR(9) CONSTRAINT NN_movil NOT NULL);

-- 3
ALTER TABLE P_PEDIDOS DROP CONSTRAINT PK_P_PEDIDOS;

-- 4
ALTER TABLE P_PEDIDOS ADD CONSTRAINT PK_P_PEDIDOS PRIMARY KEY(numPedido);

-- 5
ALTER TABLE P_EMPLEADOS MODIFY (cuota NUMBER(10,2),ventas NUMBER(10,2));

-- 6
ALTER TABLE P_EMPLEADOS ADD CONSTRAINT FK_P_EMPLEADOS_JEFE FOREIGN KEY(jefe) REFERENCES P_EMPLEADOS(numEmp);

-- 7
INSERT INTO P_OFICINAS VALUES(11, 'MADRID','CENTRO',100,100000,150000); 
INSERT INTO P_EMPLEADOS	VALUES (100,'ALEX CAMPOS',27, 11,'dir general','10/10/2007',110,10000,15000); 

SELECT * FROM P_EMPLEADOS;

INSERT INTO P_EMPLEADOS	VALUES (100,'ALEX CAMPOS',27, 11,'dir general','10/10/2007',100,10000,15000); 
/*NO SE AÑADE*/

-- 8
ALTER TABLE P_EMPLEADOS DISABLE CONSTRAINT FK_P_EMPLEADOS_JEFE;

-- 9
INSERT INTO P_EMPLEADOS	VALUES (101,'MARIA LOMAS' ,35, 11,'dir ventas','12/01/2009',110,10000,15000); 
/*NO SE AÑADE*/

-- 10
ALTER TABLE P_EMPLEADOS ENABLE CONSTRAINT FK_P_EMPLEADOS_JEFE; /*NO SE PUEDE PORQUE HAY REGISTROS NO SINCRONIZADOS*/

-- 11
DELETE FROM P_EMPLEADOS WHERE numemp=101; 

-- 12
ALTER TABLE P_EMPLEADOS ENABLE CONSTRAINT FK_P_EMPLEADOS_JEFE;

-- 13
